services:
  bdd:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD};
      - MYSQL_DATABASE=${MYSQL_DATABASE};
      - MYSQL_USER=${MYSQL_USER};
      - MYSQL_PASSWORD=${MYSQL_PASSWORD};
    volumes:
      - ./data/mysql:/var/lib/mysql
  api:
    image: apipix:v1.0
    container_name: apipix
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
  front:
    image: frontpix:v1.0
    container_name: frontpix
    ports:
      - "5173:5173"
    depends_on:
      - api