- name: Install APT dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  copy:
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Install Docker and Docker Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Create deployment directory
  file:
    path: /var/www/pixhellfest
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /var/www/pixhellfest/docker-compose.yml

- name: Copy Dockerfiles
  copy:
    src: "../../../{{ item }}"
    dest: /var/www/pixhellfest/
  loop:
    - Dockerfile.api
    - Dockerfile.front

- name: Build Docker images
  community.docker.docker_image:
    build:
      path: /var/www/pixhellfest
      dockerfile: "{{ item.dockerfile }}"
    name: "{{ item.image }}"
    tag: v1.0
    source: build
  loop:
    - { dockerfile: "Dockerfile.api", image: "apipix" }
    - { dockerfile: "Dockerfile.front", image: "frontpix" }

- name: Start containers with docker-compose
  community.docker.docker_compose_v2:
    project_src: /var/www/pixhellfest
    state: present
